release:
  github:
    owner: ekristen
    name: amihan
  prerelease: auto
builds:
  - id: amihan
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -s
      - -w
      - -X '{{ .ModulePath }}/pkg/common.SUMMARY=v{{ .Version }}'
      - -X '{{ .ModulePath }}/pkg/common.BRANCH={{ .Branch }}'
      - -X '{{ .ModulePath }}/pkg/common.VERSION={{ .Tag }}'
      - -X '{{ .ModulePath }}/pkg/common.COMMIT={{ .Commit }}'
archives:
  - id: amihan
    builds:
      - amihan
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ .Arm }}"
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - id: amihan
    ids:
      - amihan
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - ghcr.io/ekristen/amihan:v{{ .Version }}
      - ghcr.io/ekristen/amihan:{{ replace .Branch "/" "-" }}-{{ .ShortCommit }}-{{ .Timestamp }}
    build_flag_templates:
      - "--target=goreleaser"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/ekristen/amihan"
      - "--platform=linux/amd64"
signs:
  - cmd: cosign # Sign with Password
    stdin: "{{ .Env.COSIGN_PASSWORD }}"
    args: ["sign-blob", "--yes", "--tlog-upload=false", "--key=cosign.key", "--output=${signature}", "${artifact}"]
    artifacts: all
  #- ids:
  #    - amihan
  #  cmd: cosign
  #  signature: "${artifact}.sig"
  #  certificate: "${artifact}.pem"
  #  args: ["sign-blob", "--yes", "--oidc-issuer=https://token.actions.githubusercontent.com", "--output-certificate=${certificate}", "--output-signature=${signature}", "${artifact}"]
  #  artifacts: all
docker_signs:
  - ids: # Sign With Password
      - amihan
    artifacts: all
    stdin: "{{ .Env.COSIGN_PASSWORD }}"
  #- ids:
  #    - amihan
  #  artifacts: all
  #  cmd: cosign
  #  args: ["sign", "--yes", "--oidc-issuer=https://token.actions.githubusercontent.com", "--output-certificate=${certificate}", "--output-signature=${signature}", "${artifact}"]
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: '{{ trimprefix .Summary "v" }}'
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
